### ISSUE TITLE
What is the correct way to MATCH vertexes without edges?

### ISSUE THREAD

**Issue by deem0n** [apache/incubator-age#140]
I tried 

``` sql
SELECT * FROM cypher('test', 
$$MATCH (f:Engine),(t:Engine)
WHERE NOT EXISTS((f)-[]->(t))
RETURN f,t$$) as (f agtype, t agtype);
```

and it returns nothing. I am sure there are plenty not connected vertexes in my DB though.

**Comment by jrgemignani** [comment]
It is best not to assume anything about a graph. Did you create a vertex without an edge to test the command against?

**Comment by joefagan** [comment]
To find orphaned nodes...
```
SELECT * FROM cypher('test', 
$$ MATCH (f) WHERE NOT EXISTS((f)-[]-()) return f;
RETURN f $$) as (f agtype);
```

**Comment by joefagan** [comment]
@deem0n has uncovered something for sure.

The AGE behaviour is quite different from that of Neo4j sandbox (or AgensGraph) where the NOT EXISTS seems to find edges that could exist but don't. EG even for an orphaned node {name: "a"}, the only node in the graph,
```
MATCH (a),(b) WHERE NOT EXISTS((a)-[]->(b)) return a.name, b.name;
```
returns
"a", "a"
since there is no loop edge from a to a.

See more examples below and how to create them from scratch
 
```
-- create new graph
SELECT * FROM create_graph('test');

-- create a vertex with no edges
SELECT * FROM cypher('test', $$
CREATE (a:Engine {name: "orphan"})
$$) as (a agtype);

SELECT * FROM cypher('test', 
$$MATCH (f:Engine),(t:Engine)
WHERE NOT EXISTS((f)-[]->(t))
RETURN f,t$$) as (f agtype, t agtype);
```
returns 0 rows.
Equivalent commands in neo4j sandbox
```
create (a:Engine{name: "Orphan"});
MATCH (f:Engine),(t:Engine) WHERE NOT EXISTS((f)-[]->(t)) RETURN f.name, t.name;
```

returns 1 row
f.name, t.name
"Orphan", "Orphan"

With more nodes the difference in behaviour is noticeable

NOT EXISTS behaviour in AGE is not quite what is expected.

```
-- create 2 nodes and an edge
-- ({name: "F"})-[:r]->(name: "T")
SELECT * FROM cypher('test', $$
CREATE (a:Engine {name: "F"}) -[:r]- > (:engine {name: "T"})
$$) as (bla agtype);

SELECT * FROM cypher('test', 
$$MATCH (f:Engine),(t:Engine)
WHERE NOT EXISTS((f)-[]->(t))
RETURN f.name, t.name $$) as (f agtype, t agtype);
```
again returns no rows, whereas the equivalent commands in neo4j returns 5
f.name	t.name
"Orphan"	"Orphan"
"Orphan"	"F"
"F"	"Orphan"
"F"	"F"

**Comment by jrgemignani** [comment]
It should work but it doesn't and I'm not sure why. I even traced it in the debugger to no avail. We will have to create a JIRA ticket and look into it more deeply.

**Comment by joefagan** [comment]
Jira ticket is now raised and has been assigned.

**Comment by JoshInnis** [comment]
PR #141 should have resolved this issue.
