### ISSUE TITLE
support multiple label 

### ISSUE THREAD

**Issue by kevintruong** [apache/incubator-age#187]
**Is your feature request related to a problem? Please describe.**
support multi label for node 

**Describe the solution you'd like**
support multi label when create node/edge 

**Describe alternatives you've considered**

**Additional context**
```
CREATE (node:Streamer:User  { name : 'Pero', id : '7'} ) RETURN node
```

**Comment by kevintruong** [comment]
hi @jrgemignani jr
Sorry to mention you. I don't mind to bother you so fair. 
But would you please give me some info about the features: Support multi label 
I know it will take time

**Comment by jrgemignani** [comment]
Please do not tag specific individuals who are not in a thread, to bring them in. Not everyone works on the same items and you may end up not getting an answer because others will expect someone else to respond.

**Comment by jrgemignani** [comment]
At the inception of this project, it was decided to not support multiple labels. I believe this was due to performance reasons and possibly the added complexity. That doesn't mean that it isn't possible to add them. But, that would be driven by a demand for them and the difficulty in adding them. As for a workaround, you could use a property field.

**Comment by kevintruong** [comment]
thanks you, your fast response help me a lot
